FROM node
WORKDIR /dev/nodejs/app-from-github
RUN apt-get update && apt-get install -y git
RUN git clone <link of dockerized project repo>
ENV PORT=3000
RUN npm ci
CMD ["npm", "start"]

# docker build -t app-from-github-with-env
# docker run -it --init --publish 3001:3000 app-from-github-with-env:latest